# Jacobi

In [15]:
import numpy as np
import time
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

### Part a

In [16]:
A = np.array([
[0.582745, 0.48, 0.10, 0.  , 0.  ], 
 [0.48, 1.044129, 0.46, 0.10, 0.  ],
 [0.10, 0.46, 1.10431 , 0.44, 0.10],
 [0.  , 0.10, 0.44, 0.963889, 0.42],
 [0.  , 0.  , 0.10, 0.42, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

In [17]:
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[1.99528953 1.99604551 1.99609711 1.9959653  1.99509152]
[0.00863747 0.00822582 0.00802875 0.00836536 0.00889815]
[1.98713628 1.98773643 1.98774963 1.98756967 1.98683163]
[0.016914   0.01645562 0.01632132 0.01663701 0.01724335]
[1.97893448 1.97948603 1.9795206  1.97929414 1.97859658]
[0.02512187 0.02464404 0.02454374 0.02483768 0.02546937]
[1.97077879 1.9713049  1.97135409 1.97110685 1.970432  ]
[0.03326196 0.03277527 0.03269159 0.03297192 0.03361249]
[1.96268301 1.96319414 1.96325152 1.96299566 1.96233509]
[0.0413331  0.04084351 0.04076826 0.04104018 0.04168222]
[1.95465133 1.95515276 1.95521436 1.95495548 1.95430482]
[0.04933588 0.04884665 0.04877589 0.04904235 0.04968236]
[1.94668512 1.94717954 1.94724315 1.94698389 1.94634088]
[0.0572712  0.05678408 0.05671587 0.05697844 0.05761475]
[1.93878464 1.93927348 1.93933788 1.93907952 1.93844301]
[0.06513988 0.0646558  0.06458915 0.06484867 0.0654805 ]
[1.93094973 1.93143374 1.93149829 1.93124144 1.93061082]
[0.07294267 0.07246209 0.072396

### Part b

In [18]:
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[1 0]
Solution: [1 0]
Iterations: 1


### Part c

In [19]:
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[1. 1.]
[0.0000000e+00 9.9990001e-05]
[0.99990001 1.        ]
[0.         0.00019997]
[0.99980003 1.        ]
[0.         0.00029994]
[0.99970006 1.        ]
[0.        0.0003999]
[0.9996001 1.       ]
[0.         0.00049985]
[0.99950015 1.        ]
[0.         0.00059979]
[0.99940021 1.        ]
[0.         0.00069972]
[0.99930028 1.        ]
[0.         0.00079964]
[0.99920036 1.        ]
[0.         0.00089955]
[0.99910045 1.        ]
[0.         0.00099945]
[0.99900055 1.        ]
[0.         0.00109934]
[0.99890066 1.        ]
[0.         0.00119922]
[0.99880078 1.        ]
[0.         0.00129909]
[0.99870091 1.        ]
[0.         0.00139895]
[0.99860105 1.        ]
[0.        0.0014988]
[0.9985012 1.       ]
[0.         0.00159864]
[0.99840136 1.        ]
[0.         0.00169847]
[0.99830153 1.        ]
[0.         0.00179829]
[0.99820171 1.        ]
[0.        0.0018981]
[0.9981019 1.       ]
[0.        0.0019979]
[0.9980021 1.       ]
[0.         0.00209769]
[0.99790231 1.    

# Gauss-Seidel

In [20]:
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) 
            # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) 
            # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
        print(x)
    return x, max_iterations

### Part a

In [21]:
A = np.array([
[0.582745, 0.48, 0.10, 0.  , 0.  ], 
 [0.48, 1.044129, 0.46, 0.10, 0.  ],
 [0.10, 0.46, 1.10431 , 0.44, 0.10],
 [0.  , 0.10, 0.44, 0.963889, 0.42],
 [0.  , 0.  , 0.10, 0.42, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
#Print/save current time
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
#Print/save current time
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[1.99528953 1.07878435 1.3660478  1.26046623 0.72060778]
[0.87229188 0.87249783 0.98619581 1.1412702  0.88909884]
[1.10739082 0.94318261 0.96769761 1.06896363 0.95075353]
[1.05234294 0.98356346 0.97908845 1.03270942 0.97771224]
[1.01712704 0.99820654 0.98818169 1.01529249 0.9899706 ]
[1.0035053  1.00213061 0.99361016 1.00706598 0.99554366]
[0.99934155 1.00244106 0.99663098 1.00322643 0.99805153]
[0.99856745 1.0018338  0.99825676 1.00145453 0.99916455]
[0.99878866 1.00118556 0.99911196 1.00064641 0.9996504 ]
[0.99917586 1.00070819 0.99955373 1.00028257 0.99985829]
[0.99949325 1.0004025  0.99977847 1.00012112 0.99994505]
[0.99970648 1.00022093 0.99989127 1.00005066 0.99998009]
[0.99983668 1.00011813 0.9999472  1.00002052 0.99999361]
[0.99991176 1.00006186 0.99997462 1.00000795 0.99999847]
[0.9999534  1.00003184 0.99998793 1.00000288 1.        ]
[0.99997584 1.00001615 0.99999432 1.00000092 1.00000035]
[0.99998767 1.00000808 0.99999735 1.00000022 1.00000033]
[0.9999938  1.000004   0.999998

### Part b

In [22]:
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
#Print/save current time
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
#Print/save current time
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[1 0]
Solution: [1 0]
Iterations: 1


### Part c

In [23]:
A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
#Print/save current time
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
#Print/save current time
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[1.0000000e+00 9.9990001e-05]
[9.99900010e-01 1.99970004e-04]
[9.9980003e-01 2.9994001e-04]
[9.9970006e-01 3.9990002e-04]
[9.99600100e-01 4.99850035e-04]
[9.99500150e-01 5.99790056e-04]
[9.99400210e-01 6.99720084e-04]
[9.9930028e-01 7.9964012e-04]
[9.99200360e-01 8.99550165e-04]
[0.99910045 0.00099945]
[0.99900055 0.00109934]
[0.99890066 0.00119922]
[0.99880078 0.00129909]
[0.99870091 0.00139895]
[0.99860105 0.0014988 ]
[0.9985012  0.00159864]
[0.99840136 0.00169847]
[0.99830153 0.00179829]
[0.99820171 0.0018981 ]
[0.9981019 0.0019979]
[0.9980021  0.00209769]
[0.99790231 0.00219747]
[0.99780253 0.00229724]
[0.99770276 0.002397  ]
[0.997603   0.00249675]
[0.99750325 0.00259649]
[0.99740351 0.00269622]
[0.99730378 0.00279594]
[0.99720406 0.00289565]
[0.99710435 0.00299535]
[0.99700465 0.00309505]
[0.99690495 0.00319473]
[0.99680527 0.0032944 ]
[0.9967056  0.00339406]
[0.99660594 0.00349371]
[0.99650629 0.00359335]
[0.99640665 0.00369298]
[0.99630702 0.0037926 ]
[0.9962074  0.00389221]
[0