## Part a

In [26]:
import time

In [27]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start_time = time.perf_counter()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            end_time = time.perf_counter()
            return x_new, k, (end_time - start_time)
        x = x_new
        print(x)
    end_time = time.perf_counter()
    return x, max_iterations, (end_time - start_time)

In [28]:
# Example usage
A = np.array([[10,-1,2,0,0],[-1,11,-1,3,0],[2,-1,10,-1,0],[0,3,-1,8,-2],[0,0,0,-2,9]])
b = np.array([14,30,26,25,37])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations, elapsed_time = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.8f}")

[1 2 2 3 4]
Solution: [1 2 2 3 4]
Iterations: 1
Time: 0.00066906


In [29]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start_time = time.perf_counter()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) 
            # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) 
            # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            end_time = time.perf_counter()
            return x_new, k, (end_time - start_time)
        x = x_new
        print(x)
    end_time = time.perf_counter()
    return x, max_iterations, (end_time - start_time)


In [30]:
# Example usage
A = np.array([[10,-1,2,0,0],[-1,11,-1,3,0],[2,-1,10,-1,0],[0,3,-1,8,-2],[0,0,0,-2,9]])
b = np.array([14,30,26,25,37])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations, elapsed_time = gauss_seidel(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.8f}")

[1 2 2 2 4]
[1 2 2 3 4]
Solution: [1 2 2 3 4]
Iterations: 2
Time: 0.00095874


## Part b

In [31]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start_time = time.perf_counter()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            end_time = time.perf_counter()
            return x_new, k, (end_time - start_time)
        x = x_new
        print(x)
    end_time = time.perf_counter()
    return x, max_iterations, (end_time - start_time)

In [32]:
# Example usage
A = np.array([[1,2,3,0,0],[2,1,2,3,0],[3,2,1,2,3],[0,3,2,1,2],[0,0,3,2,1]])
b = np.array([14,22,33,26,22])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations, elapsed_time = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.8f}")

[14 22 33 26 22]
[-129 -150 -171 -150 -129]
[ 827 1072 1407 1076  835]
[-6351 -7674 -9249 -7674 -6351]
[43109 54244 68835 54248 43117]
[-314979 -386610 -475629 -386610 -314979]
[2200121 2741068 3436347 2741072 2200129]
[-15791163 -19496130 -24164997 -19496130 -15791163]
[111487265 138400732 172731531 138400736 111487273]
[ -794996043  -983639778 -1222526517  -983639778  -794996043]
[5634859121 6985964476 8704535403 6985964480 5634859129]
[-40085535147 -49636682466 -61753012629 -49636682466 -40085535147]
[284532402833 352587142972 439059940779 352587142976 284532402841]
[-2022354108267 -2504946116130 -3117542988885 -2504946116130
 -2022354108267]
[14362521198929 17794632542716 22153909114155 17794632542720
 14362521198937]
[-102050992427883 -126416758254306 -157353657364437 -126416758254306
 -102050992427883]
[ 724894488601937  898059574347580 1117972987584555  898059574347584
  724894488601945]
[-5150038111448811 -6379913675415714 -7941605229001941 -6379913675415714
 -5150038111448811]

<ipython-input-31-2614a9ca5e3c>:9: RuntimeWarning: overflow encountered in long_scalars
  s = sum(A[i][j] * x[j] for j in range(n) if j != i)


In [33]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    start_time = time.perf_counter()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) 
            # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) 
            # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            end_time = time.perf_counter()
            return x_new, k, (end_time - start_time)
        x = x_new
        print(x)
    end_time = time.perf_counter()
    return x, max_iterations, (end_time - start_time)

In [34]:
# Example usage
A = np.array([[1,2,3,0,0],[2,1,2,3,0],[3,2,1,2,3],[0,3,2,1,2],[0,0,3,2,1]])
b = np.array([14,22,33,26,22])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations, elapsed_time = gauss_seidel(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")
print(f"Time: {elapsed_time:.8f}")

[ 14  -6   3  38 -63]
[  17 -132  359 -170 -715]
[ -799  1412  2091 -6962  7673]
[ -9083  34892 -51597 -16802 188417]
[  85021  -16420 -753837 1180126  -98719]
[  2294365  -6621412   4295667  11470366 -35827711]
[    355837  -43714084  170903091 -139008482 -234692287]
[ -425281091   925781468   406374195 -3120708194  5022293825]
[ -3070685507  14690747228 -28994902989   3872976670  79238755649]
[  57603214525  -68835553060 -280600757709  609230663326 -376659053503]
[   979473379261  -3225437233060   3423970162227   3581689481758
 -17435289450175]
[ -3821036020547  -9950936728612  76507470905907 -88291552725602
 -52939307266495]
[ -209620539260483   531100794885980   -97938944739789 -1291545880645346
  2876908595510081]
[  -768384755552579   5607285042520796 -14957049843623372
   7338427368664220  30194294793541696]
[  33656579445828536  -59414341310402968  -87400794834633168
  292656024013391872 -323109663522884224]
[  381031067124705472 -1465228616620320256  2171380974408392960
   699

<ipython-input-33-edf454ca5a86>:9: RuntimeWarning: overflow encountered in long_scalars
  s1 = sum(A[i][j] * x_new[j] for j in range(i))
<ipython-input-33-edf454ca5a86>:11: RuntimeWarning: overflow encountered in long_scalars
  s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
<ipython-input-33-edf454ca5a86>:13: RuntimeWarning: overflow encountered in long_scalars
  x_new[i] = (b[i] - s1 - s2) / A[i][i]


## DISCUSSION

For part a, both of the methods converge. However, the Jacobi iteration runs one iteration while the Gauss-Seidel requires two iterations. In addition to this, the Jacobi iteration required approximately .0003 less time to run than the Gauss-Seidel. 

For part b, neither of the methods converged as they both reached the maximum runs (100) without having found a true solution. They both took around .035 seconds although the Jacobi was still faster than the Gauss-Seidel by a fraction of a second.  