Linear Algebra in Python

In [1]:
import numpy as np

In [3]:
#creating the vector
v1 = np.array([1, 2, 3]) 
v2 = np.array([4, 5, 6])

In [5]:
print (v1)
print (v2)

[1 2 3]
[4 5 6]


In [6]:
v_add = v1 + v2
v_sub = v1 - v2

In [7]:
print (v_add)
print (v_sub)

[5 7 9]
[-3 -3 -3]


In [8]:
scalar = 2
v_scaled = scalar * v1

In [9]:
print (v_scaled)

[2 4 6]


In [10]:
dot_product = np.dot(v1, v2)

In [11]:
print (dot_product)

32


In [13]:
magnitude_v1 = np.linalg.norm(v1)
print (magnitude_v1)

3.7416573867739413


In [21]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print (A)
print ()

B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print (B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [22]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print ("A+C=\n", matrix_add)
print ("A-C=\n", matrix_sub)

A+C=
 [[ 2  4  6]
 [ 8 10 12]]
A-C=
 [[0 0 0]
 [0 0 0]]


In [23]:
matrix_mul = np.dot(A, B)

print(matrix_mul)

[[ 66  72  78]
 [156 171 186]]


In [24]:
transpose_A = A.T
print(transpose_A)

[[1 4]
 [2 5]
 [3 6]]


In [28]:
a = np.array([[2, 3], [4, -1]])
b = np.array([5,3])
print(a)
print(b)
x = np.linalg.solve(a,b)
print('Solution:')
print(x)

[[ 2  3]
 [ 4 -1]]
[5 3]
Solution:
[1. 1.]


In [29]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vectors = np.linalg.eig(A)

In [31]:
print("eiganvalue:", e_value)
print("eiganvector:", e_vectors)

eiganvalue: [3. 1.]
eiganvector: [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [33]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print(A)
print(A_inv)

[[4 7]
 [2 6]]
[[ 0.6 -0.7]
 [-0.2  0.4]]


In [35]:
identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


Identity Matrix:

1 0 0

0 1 0

0 0 1

# SVD in Python

# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
# Perform SVD
U, sigma, Vt = np.linalg.svd(A)
print("U matrix:\n", U)
print("Sigma values:", sigma)
print("V^T matrix:\n", Vt)
